config/routes.rb
Rails.application.routes.draw do
  get 'file_items/index'

  get 'file_items/new'

  get 'file_items/create'

  get 'file_items/destroy'

  get     'signup'  => 'users#new'

  root    'static_pages#home'
  get     'help'    => 'static_pages#help'
  get     'about'   => 'static_pages#about'
  get     'contact' => 'static_pages#contact'

  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :users
  resources :file_items, only: [:index, :new, :create, :destroy]

end

app/models/file_item.rb
class FileItem < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader

  validates :name, presence: true
  validates :user, presence: true

  belongs_to :user


  before_save :update_file_item_attributes

  private

  def update_file_item_attributes
    if !name.present?
      self.name = 'asad'
    end

    # if model.present? && asset_changed?
    #   self.content_type = asset.file.content_type
    #   self.size = asset.file.size
    # end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token               # with this and appropriate functions we are recreating the principle behind has_secure_password ie. remember the stuff without saving it into the database
  before_save { self.email = email.downcase } #supposed to verify that the fuckers are unique for sure
                                              #before_save is a callback, guess when it gets called

  validates :name,  presence: true, length: { maximum: 255 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true


  #uz has_secure_password možeš koristit 2 virtualna polja "password" i "password_confirmation"
  #koje automatski prepoznaje kao šifre i radi hash na njima
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :file_items, inverse_of: :user, dependent: :destroy
  accepts_nested_attributes_for :file_items


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forget user ie. clears remember_digest atribute in the table users for this user
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper #helpers are automatically included in Rails views; by including the module into the base class of all controllers (the Application controller), we arrange to make them available in our controllers as well
end

app/controllers/file_items_controller.rb
class FileItemsController < ApplicationController
  def index
    @file_items = @current_user.file_items.all
  end

  def new
    @user = User.find(session[:user_id])

    @file_item = @user.file_items.new

  end

  def create
    # if params[:attachment]
    #   #picture_path_params = params[:picture][:picture_path]
    #   #create a new tempfile named fileupload
    #   tempfile = Tempfile.new("fileupload")
    #   tempfile.binmode
    #   #get the file and decode it with base64 then write it to the tempfile
    #   tempfile.write(Base64.decode64(params["attachemnt"]))
    #
    #   #create a new uploaded file
    #   uploaded_file = ActionDispatch::Http::UploadedFile.new(:tempfile => tempfile, :filename => picture_path_params["filename"], :original_filename => picture_path_params["original_filename"])
    #
    #   #replace picture_path with the new uploaded file
    #   params[:file_item] =  uploaded_file

    @user = User.find(session[:user_id])

    @file_item = @user.file_items.new(file_item_params)

    @file_item.name = :original_filename if @file_item.name == ""

    respond_to do |format|
      if @file_item.save
        format.html { redirect_to user_path @user.id, flash[:success] = "File has been uplaoded" }
        format.json { render json: @file_item, status: :created, location: @file_item }
      else
        format.html { render action: "new" }
        format.json { render json: @file_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(session[:user_id])

    @file_item = FileItem.find(params[:id])
    @file_item.destroy
    respond_to do |format|

      format.html { redirect_to user_path @user.id, flash[:danger] = "File has been deleted" }
      format.json {render json: @file_item, status: :deleted}
    end
  end

  private
    def file_item_params
      params.require(:file_item).permit(:name, :attachment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user #TODO: login
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash[:danger] = 'Invalid email or password' #TODO: error mesgs
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    @user = User.find(params[:id])
    @files = @user.file_items.all
  end

  def new #ako ovaj pogled prođe izvršava se "create"
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Oblak project!"
      redirect_to @user #equivalent: redirect_to user_url(@user)
    else
      render 'new' #ako je fejlo vrati ga na početak tj. na new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Project Oblak"
    if page_title.empty?
      base_title
    end
    else
      page_title + " | " + base_title
  end
end

app/helpers/file_items_helper.rb
module FileItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  #As with log_in, sessions_controller defers the real work to the Sessions helper, where we define a remember method that calls user.remember, thereby generating a remember token and saving its digest to the database. It then uses cookies to create permanent cookies for the user id and remember token
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end


  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?=s#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/file_items/create.html.erb
<h1>FileItems#create</h1>
<p>Find me in app/views/file_items/create.html.erb</p>

app/views/file_items/destroy.html.erb
<h1>FileItems#destroy</h1>
<p>Find me in app/views/file_items/destroy.html.erb</p>

app/views/file_items/index.html.erb
<br />
<%= link_to "New File", new_file_item_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Download Link</th>
    <th>&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <% @file_items.each do |file| %>
      <tr>
        <td><%= file.name %></td>
        <td><%= link_to "Download", file.attachment_url %></td>
        <td><%= button_to "Delete",  file, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{file.name}?" %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/file_items/new.html.erb
<div class="well">
  <%= form_for @file_item, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Project Oblak</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "OBLAK", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Profile", current_user %></li>
            <li class="divider"></li>
            <li> <%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %> <!-- equivalent?: <div class="alert alert-<%= message_type %>"><%= message %></div> -->
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>
  Projekt Oblak kao seminar iz kolegija Mreže Računala 2
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<h1 class="center jumbotron">Welcome to Oblak</h1>
<h2>This is the home page of Project Oblak</h2>

<%= link_to "Register", signup_path, class: "btn btn-lg btn-primary" %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offest-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation"%>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create account", class: "btn btn-primary" %>

    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<br />
<%= link_to "New File", new_file_item_path(@current_user), class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Download Link</th>
    <th>&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <% @files.each do |file| %>
      <tr>
        <td><%= file.name %></td>
        <td><%= link_to "Download", file.attachment_url, class: "btn btn-block btn-success"%></td>
        <td><%= button_to "Delete",  file, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{file.name}?" %></td>
      </tr>
  <% end %>
  </tbody>
</table>